version: '3'

services:

  sync:
      build: .
      image: cncli
      restart: always
      volumes:
      - ./db:/db
      command: cncli sync --host 49.12.86.157 --port 3001 -d /db/cncli.db

  leaderlog:
      build: .
      image: cncli
      volumes:
      - ./db:/db
      - ./keys:/keys
      - ./ledgerstate:/ledgerstate/
      command: cncli leaderlog --pool-id 3bd3996595321d951291b11e1331061c5d8659d9e69390536dfc922c -d /db/cncli.db --pool-vrf-skey /keys/vrf.skey --byron-genesis /keys/mainnet-byron-genesis.json --shelley-genesis /keys/mainnet-shelley-genesis.json --ledger-state /ledgerstate/ledgerstate.json --ledger-set ${LOG}
